### ISSUE TITLE
some error with test_ship.py

### ISSUE THREAD

**Issue by luozhexin** [Zengyi-Qin/bcbf#1]
(adacbf) wsco@W513:~/luozhexin/adacbf$ python scripts/test_ship.py --vis 1 --env river
Traceback (most recent call last):
  File "/home/wsco/luozhexin/adacbf/scripts/test_ship.py", line 143, in <module>
    main(args.env, args.preplanned_traj, args.npc_speed, args.vis, args.save_traj)
  File "/home/wsco/luozhexin/adacbf/scripts/test_ship.py", line 112, in main
    p = PatchCollection([Polygon(rect, True)], alpha=0.1, color='darkred')
TypeError: __init__() takes 2 positional arguments but 3 were given

Environment：
python 3.9
cvxpy==1.2.1
gurobipy==9.1.2
matplotlib==3.8.1
scipy=1.10.1
torch=1.9.1

**Comment by luozhexin** [comment]
matplotlib==3.3.0
